### ISSUE TITLE
Move master to main branch.

### ISSUE THREAD

**Issue by bryanjbelanger** [puppetlabs/puppetlabs-bolt_shim#22]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]

**Comment by donoghuc** [comment]
We have created an internal ticket to track this work and will get it pulled in to an upcoming sprint. Thanks!

**Comment by donoghuc** [comment]
We have made a pass through our CI and docs to make the switch to main. I will delete the `master` branch next week.
