### ISSUE TITLE
Running Plans with Host name Input

### ISSUE THREAD

**Issue by Rph5132** [puppetlabs/puppetlabs-bolt_shim#3]
In order to leverage the orchestrator when using tasks/plans, I'm making use of bolt_shim. In order for bolt_shim to work you must preface your --node with pcp://<master>. This works fine and well until you have a plan that allows for user input that is a node/hostname. If you feed it 'pcp://', it simply can't find it because it's not the accurate fqdn.

How can you effectively handle all these nested node parameters when running plans?

**Comment by MikaelSmith** [comment]
This might be worth following up with on Bolt. I'm not quite sure what you're describing, but generally I'd avoid writing plans that expect or attach a particular protocol (`pcp`, `ssh`, `winrm`). Bolt inventory files are one way to support more complex sets of nodes.

**Comment by MikaelSmith** [comment]
Instead of using `pcp://`, try `--transport pcp` or an [inventory file](https://puppet.com/docs/bolt/1.x/inventory_file.html).
